# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups


INSERT INTO PUBLIC.USER_ENTITY (ID, LOGIN, PASSWORD, DROPBOX_ACCESS_KEY, DRIVE_ACCESS_TOKEN, DRIVE_REFRESH_TOKEN, GOOGLE_EMAIL, DROPBOX_UID, DRIVE_TOKEN_EXPIRES) VALUES (1, 'test', '123', 'BAus-dLEjW8AAAAAAAAAAVDysztTsSGkiwlJV7Fm6lvHYxbp0-QdBsyE_Hb_7dYd', '7hlztwsgm4v8l2f', 'C6jC5Vm8aiRDiNwy', null, '192670402', null);
INSERT INTO PUBLIC.SONG_ENTITY (ID, CLOUD_ID, LAST_TIME_ACCESSED, FILE_NAME, FILE_SIZE, METADATA_TITLE, METADATA_ARTIST, METADATA_ALBUM, METADATA_YEAR, METADATA_GENRE, METADATA_LENGTH_SECONDS, USER_ID) VALUES (1, 1, '2014-09-13 17:28:04.517', 'Shots.mp3', 0, 'www.VanStation.blogspot.com', 'www.VanStation.blogspot.com', '', '0', '', null, 1);

# --- !Downs

